server:
  port: 8888
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.187.20.7:3306/bd_center?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: Lichuang@2015
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true